Name:           perl-App-CPANtoRPM
Version:        1.15
Release:        3%{?dist}
Summary:        Library used by the cpantorpm tool
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/App-CPANtoRPM/
Source0:        http://www.cpan.org/modules/by-module/App/App-CPANtoRPM-%{version}.tar.gz
Source1:        App-CPANtoRPM.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(IO::File)
BuildRequires:  perl(POSIX)
BuildRequires:  perl(Test::Inter) >= 1.09
BuildRequires:  perl(Test::More)
BuildRequires:  perl(locale)
Requires:       perl(IO::File)
Requires:       perl(POSIX)
Requires:       perl(locale)
Requires:       /usr/bin/strace
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The cpantorpm tool is a script to take a package from CPAN and turn it into
an RPM. Please refer to the documentation for cpantorpm for more
information.

%prep
%setup -q -n App-CPANtoRPM-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc LICENSE META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*
%{_bindir}/*

%changelog
* Mon Mar 03 2025 Michael R. Davis <mrdvt92@yahoo.com> 1.15-1
- Specfile autogenerated by cpanspec 1.78.
